theme: jekyll-theme-minimal
show_downloads: ["true"]
logo: /assets/imgs/mutapk.png
title: MutAPK
tsdllogo: /assets/imgs/horizontalLightBrackgrounds.png

navigation:
  - title: Video
    link: /video.hmtl
